export enum Logos {
  'Me' = '/logos/me.jpg',
  'SHV' = '/logos/shv.webp',
  'OneTwentyOne' = '/logos/121.webp',
  'Altum' = '/logos/leaf.svg',
  'TypeScript' = '/logos/typescript.svg',
  'JavaScript' = '/logos/javascript.svg',
  'Next' = '/logos/next.svg',
  'React' = '/logos/react.svg',
  'Node' = '/logos/node.svg',
  'PostgreSQL' = '/logos/postgresql.svg',
  'GraphQL' = '/logos/graphql.svg',
  'Express' = '/logos/express.svg',
  'Prisma' = '/logos/prisma.svg',
  'AWS' = '/logos/aws.svg',
  'GCP' = '/logos/gcp.svg',
  'Azure' = '/logos/azure.svg',
  'Tailwind' = '/logos/tailwind.svg',
  'Bootstrap' = '/logos/bootstrap.svg',
  'Sass' = '/logos/sass.svg',
  'Swift' = '/logos/swift.svg',
  'DigitalOcean' = '/logos/digital-ocean.svg',
  'Astro' = '/logos/astro.svg',
  'ReactRouter' = '/logos/react-router.svg',
  'Bun' = '/logos/bun.svg',
  'Sentry' = '/logos/sentry.svg',
  'Cornell' = '/logos/cornell.png',
}

const logoAlt: Record<Logos, string> = {
  [Logos.Me]: 'Alex Godfrey',
  [Logos.SHV]: 'Sutter Hill Ventures',
  [Logos.OneTwentyOne]: 'OneTwentyOne',
  [Logos.Altum]: 'Altum Labs',
  [Logos.TypeScript]: 'TypeScript',
  [Logos.JavaScript]: 'JavaScript',
  [Logos.Next]: 'Next.js',
  [Logos.React]: 'React',
  [Logos.Node]: 'Node.js',
  [Logos.PostgreSQL]: 'PostgreSQL',
  [Logos.GraphQL]: 'GraphQL',
  [Logos.Express]: 'Express',
  [Logos.Prisma]: 'Prisma',
  [Logos.AWS]: 'Amazon Web Services',
  [Logos.GCP]: 'Google Cloud Platform',
  [Logos.Azure]: 'Microsoft Azure',
  [Logos.Tailwind]: 'Tailwind CSS',
  [Logos.Bootstrap]: 'Bootstrap',
  [Logos.Sass]: 'Sass',
  [Logos.Swift]: 'Swift',
  [Logos.DigitalOcean]: 'DigitalOcean',
  [Logos.Astro]: 'Astro',
  [Logos.ReactRouter]: 'React Router',
  [Logos.Bun]: 'Bun',
  [Logos.Sentry]: 'Sentry',
  [Logos.Cornell]: 'Cornell University',
};

export function Logo({ name, className }: { name: Logos; className?: string }) {
  return <img src={name} alt={logoAlt[name]} className={className} loading="lazy" />;
}
